environment:
  global:
    RUSTFLAGS: -Zunstable-options -Ctarget-feature=+crt-static
    RUST_BACKTRACE: 1
    CARGO_INCREMENTAL: 0   # should turn this back on when fixed!
  matrix:
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: Install-Product node 10
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - npm i
  - cargo test
  - cargo run --example major_libs --release

branches:
  only:
    - master