language: rust
sudo: false
matrix:
  include:
    - rust: stable
      install: true
      cache: cargo
      before-install: npm i
      script:
        - cargo test
        - cargo run --example major_libs --release
notifications:
  email: never