language: rust
sudo: false
matrix:
  include:
    - rust: stable
      install: npm i
      cache: cargo
      script:
        - cargo test
        - cargo run --example major_libs --release
notifications:
  email: never