language: rust
sudo: false
matrix:
  include:
    - rust: stable
      install:
        - npm i
      cache:
        - directories:
          - /home/travis/.cargo
          - moz-central
          - node_modules
      before_cache:
        - rm -rf /home/travis/.cargo/registry
      script:
        - cargo test --features moz_central
        - cargo run --example major_libs
      stages:
        after_script:
          - if branch in (master, next)
notifications:
  email: never