[package]
name = "js_parse"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]

[dependencies]
combine = "3.3"
reqwest = "0.8"
# estree-rs = { path = "../estree-rs/" }

[lib]
name = "js_parser"

[[bin]]
name = "js_parse"