name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: install js test libs from npm
      run: npm install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
